#!/bin/bash                                                                        

numb=$1

case "$numb" in
    "1") echo ""
         echo "|"
   echo "|"
	 echo "|"
         echo "|"
         echo "|"
         echo "|"
         echo "|"
	 echo "|"
         echo "|"
         echo "|"
         echo "|" ;;
    "2") echo ""
         echo "|---------------"
         echo "|"
      	 echo "|"
         echo "|"
         echo "|"
         echo "|"
         echo "|"
         echo "|"
         echo "|"
         echo "|"
         echo "|" ;;

      "3") echo ""
         echo "|---------------"
         echo "|              ?"
         echo "|             / \ "
         echo "|             \ / "
         echo "|"
         echo "|"
         echo "|"
         echo "|"
         echo "|"
         echo "|"
         echo "|" ;;

   "4") echo ""
         echo "|---------------"
         echo "|              ?"
         echo "|             / \ "
         echo "|             \ / "
         echo "|              |  "
         echo "|              |  "
         echo "|              |   "
         echo "|              |  "
         echo "|"
         echo "|"
         echo "|" ;;

   "5") echo ""
         echo "|---------------"
         echo "|              ?"
         echo "|             / \ "
         echo "|             \ / "
         echo "|              |  "
         echo "|             /|\  "
         echo "|            / | \  "
         echo "|              |   "
         echo "|"
         echo "|"
         echo "|" ;;

   "6") echo ""
         echo "|---------------"
         echo "|              ?"
         echo "|             / \ "
         echo "|             \ / "
         echo "|              |  "
         echo "|             /|\  "
         echo "|            / | \  "
         echo "|              |   "
         echo "|             /     "
         echo "|            /      "
         echo "|" ;;
   "7") echo ""
         echo "|---------------"
         echo "|              ?"
         echo "|             / \ "
         echo "|             \ / "
         echo "|              |  "
         echo "|             /|\  "
         echo "|            / | \  "
         echo "|              |   "
         echo "|             / \      "
         echo "|            /   \     "
         echo "|" ;;

    *)   echo "Koniec"
esac
